---
- hosts: server
  tasks:
    - name: Provision EC2 instance
      ec2:
         key_name: Ansible
         region: us-east-2
         instance_type: t2.micro
         image: ami-00dfe2c7ce89a450b
         wait: yes
         wait_timeout: 500
         count: 1
         instance_tags:
            Name: AWS-Ansible
         volumes:
            - device_name: /dev/xvda
              volume_type: gp2
              volume_size: 8
         monitoring: yes
         vpc_subnet_id: subnet-b67b49fa
         assign_public_ip: yes
         group: ansible
      register: ec2

    - name: Wait for SSH to come up
      wait_for:
          host: "{{ item.public_dns_name }}"
          port: 22
          delay: 60
          timeout: 320
          state: started
      with_items: "{{ ec2.instances }}"
